# Generated by Django 3.2 on 2023-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_note',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
