# Generated by Django 3.2 on 2023-03-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_note',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
