# Generated by Django 3.2 on 2023-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_frame',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_paper',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
