# Generated by Django 3.2 on 2023-03-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Commission',
        ),
    ]
