# Generated by Django 3.2 on 2023-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.CharField(blank=True, choices=[('o', 'Oak'), ('w', 'Walnut'), ('b', 'Black')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='paper',
            field=models.CharField(blank=True, choices=[('m', 'Matte'), ('g', 'Glossy')], max_length=1, null=True),
        ),
    ]
